spring:
  datasource:
    url: jdbc:h2:~/liquibase
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
services:
  address:
    server: http://localhost:8181
    auth:
      user: user1
      password: password1
    endpoints:
      getAddress: /address/{id}